{
 "title": "Dashboard Demo",
 "time": { "from": "2023-11-30T22:54:30.000Z", "to": "2024-01-11T23:13:30.000Z" },
 "templating": {
  "list": [
   {
    "name": "specie",
    "label": "specie",
    "query": "SELECT DISTINCT common_name\t\nFROM sensor_data\t\nORDER BY common_name;"
   },
   {
    "name": "exclude",
    "query": "SELECT DISTINCT common_name\t\nFROM sensor_data\t\nORDER BY common_name;"
   },
   { "name": "confidence", "label": "Confidence Level (%) >=", "query": "0,0.5,0.6,0.7,0.8,0.9,1" }
  ]
 },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Observations",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  count(*) AS total_detections\nFROM sensor_data\nWHERE $__timeFilter(time)\n  AND common_name IN ($specie)\n  AND common_name NOT IN(${exclude:sqlstring})\n  AND confidence >= $confidence \n"
    }
   ]
  },
  {
   "title": "Avg Confidence",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  avg(confidence) AS avg_confidence\nFROM sensor_data\nWHERE $__timeFilter(time)\n  AND common_name IN ($specie)\n  AND common_name NOT IN(${exclude:sqlstring})\n  AND confidence >= $confidence \n"
    }
   ]
  },
  {
   "title": "Unique Species",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(DISTINCT common_name) AS unique_species\nFROM sensor_data\nWHERE $__timeFilter(time)\n  AND common_name IN ($specie)\n  AND common_name NOT IN(${exclude:sqlstring})\n  AND confidence >= $confidence \n"
    }
   ]
  },
  {
   "title": "Avg Audio Length (Sec)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  AVG(end_seconds - start_seconds) AS avg_audio_length_seconds\nFROM sensor_data\nWHERE $__timeFilter(time)\n  AND common_name IN ($specie)\n"
    }
   ]
  },
  {
   "title": "Window Length (hrs)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  extract(\n    epoch\n    FROM $__timeTo()::timestamp\n      - $__timeFrom()::timestamp\n  ) \n  / 3600.0\n  AS window_hours;\n"
    }
   ]
  },
  {
   "title": "Avg Detections per Hour",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(*) * 3600.0\n    / extract(\n        epoch\n        FROM $__timeTo()::timestamp\n          - $__timeFrom()::timestamp\n      )\n  AS avg_per_hour\nFROM sensor_data\nWHERE $__timeFilter(time);\n"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT\n  date_trunc('day', time)                        AS \"time\",\n  count(*)                                        AS \"total observations\",\n  count(DISTINCT scientific_name)                  AS \"species count\"\nFROM sensor_data\nWHERE $__timeFilter(time)\nGROUP BY 1\nORDER BY 1;\n"
    }
   ]
  },
  {
   "title": "Activity Pattern Detection Distribution (Hrs)",
   "type": "heatmap",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "rawSql": "SELECT\n  extract(hour from time) AS detection_hour,\n  COUNT(*) AS \" \"\nFROM sensor_data\nWHERE $__timeFilter(time)\n  AND common_name IN ($specie)\n  AND common_name NOT IN(${exclude:sqlstring})\n  AND confidence >= $confidence \nGROUP BY detection_hour\nORDER BY detection_hour;"
    }
   ]
  },
  {
   "title": "Species Distribution",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 21 },
   "targets": [
    {
     "rawSql": "SELECT\n  common_name,\n  COUNT(*) AS total_by_species\nFROM sensor_data\nWHERE $__timeFilter(time)\n  AND common_name IN ($specie)\n  AND common_name NOT IN (${exclude:sqlstring})\n  AND confidence >= $confidence \nGROUP BY common_name\nORDER BY total_by_species DESC;\n"
    }
   ]
  },
  {
   "title": "Question it answers: how do detection counts rise and fall over time",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 16, "x": 8, "y": 21 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(time, '1d'),     \n  common_name                       AS \"species\",\n  COUNT(*)                          AS \"Total\"\nFROM sensor_data\nWHERE\n  $__timeFilter(time)               -- respects your dashboard time picker\n  AND common_name IN ($specie)      -- template var for included species\n  AND common_name NOT IN (${exclude:sqlstring})  -- template var for excluded species\n  AND confidence >= $confidence     -- template var for minimum confidence\nGROUP BY 1, common_name             -- group by your time bucket + species\nORDER BY 1                          -- sort by time asc\n"
    }
   ]
  },
  {
   "title": "Question it answers: Of a day's total detections, which species contributed how much",
   "type": "barchart",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(time, '1d'),     \n  common_name                       AS \"species\",\n  COUNT(*)                          AS \"Total\"\nFROM sensor_data\nWHERE\n  $__timeFilter(time)               -- respects your dashboard time picker\n  AND common_name IN ($specie)      -- template var for included species\n  AND common_name NOT IN (${exclude:sqlstring})  -- template var for excluded species\n  AND confidence >= $confidence     -- template var for minimum confidence\nGROUP BY 1, common_name             -- group by your time bucket + species\nORDER BY 1                          -- sort by time asc\n"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "status-history",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 47 },
   "targets": [
    {
     "rawSql": "SELECT\n  date_trunc('day', time)     AS date,\n  common_name                 AS species,\n  COUNT(*)                    AS cnt\nFROM sensor_data\nWHERE $__timeFilter(time)\n  AND confidence >= $confidence\n  AND common_name IN ($specie)\nGROUP BY 1,2\nORDER BY 1,2;\n"
    }
   ]
  },
  {
   "title": "Species Detection Confidence Over Time",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 59 },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  confidence AS \"c\",\n  scientific_name\nFROM sensor_data\nWHERE $__timeFilter(time)\n  AND common_name IN ($specie)\n  AND common_name NOT IN(${exclude:sqlstring})\n  AND confidence >= $confidence \nORDER BY time ASC\n"
    }
   ]
  },
  {
   "title": "Species Detection Confidence Over Time",
   "type": "candlestick",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 70 },
   "targets": [
    {
     "rawSql": "WITH stats AS (\n  SELECT\n    $__timeGroup(time, '1d')                   AS bucket_time,          -- daily buckets\n    min(confidence)                             AS low,                 -- whisker bottom\n    percentile_cont(0.25) WITHIN GROUP (ORDER BY confidence) AS open,   -- Q1\n    percentile_cont(0.50) WITHIN GROUP (ORDER BY confidence) AS median, -- median\n    percentile_cont(0.75) WITHIN GROUP (ORDER BY confidence) AS close,  -- Q3\n    max(confidence)                             AS high,                -- whisker top\n    count(*)                                    AS volume               -- count of points\n  FROM sensor_data\n  WHERE $__timeFilter(time)\n  GROUP BY 1\n)\nSELECT\n  bucket_time   AS \"time\", \n  open, \n  high, \n  low, \n  close, \n  median, \n  volume\nFROM stats\nORDER BY bucket_time;\n"
    }
   ]
  },
  {
   "title": "Sensor 2",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 81 },
   "targets": [
    {
     "rawSql": "WITH bucketed AS (\r\n  SELECT\r\n    width_bucket(confidence, 0.0, 1.0, 25) AS bucket,\r\n    count(*)                         AS detections\r\n  FROM sensor_data\r\n  WHERE $__timeFilter(time)\r\n  GROUP BY bucket\r\n)\r\nSELECT\r\n  -- format the lower edge of each bucket as text for the X-axis\r\n  ((bucket - 1) * (1.0/25))::numeric(4,2)::text AS confidence_bucket,\r\n  detections\r\nFROM bucketed\r\nORDER BY confidence_bucket;\r\n"
    }
   ]
  },
  {
   "title": "Raw Table Integration",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 92 },
   "targets": [
    {
     "rawSql": "SELECT\n  time,\n  start_seconds,\n  end_seconds,\n  scientific_name,\n  common_name,\n  confidence,\n  sensor_id\nFROM sensor_data\nWHERE $__timeFilter(time)\n  AND common_name IN ($specie)\n  AND common_name NOT IN(${exclude:sqlstring})\n  AND confidence >= $confidence \n"
    }
   ]
  },
  {
   "title": "DRAFT: Sprint 4 Dashboard Iteration",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 102 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Detections",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 84 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT \n  count(*) AS total_detections\nFROM sensor_data\nWHERE $__timeFilter(time)\n  AND common_name IN ($specie)\n  AND common_name NOT IN(${exclude:sqlstring})\n  AND confidence >= $confidence \n"
      }
     ]
    },
    {
     "title": "Unique Species",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 4, "y": 84 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  count(DISTINCT common_name) AS unique_species\nFROM sensor_data\nWHERE $__timeFilter(time)\n  AND common_name IN ($specie)\n  AND common_name NOT IN(${exclude:sqlstring})\n  AND confidence >= $confidence \n"
      }
     ]
    },
    {
     "title": "Avg Confidence",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 8, "y": 84 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT \n  avg(confidence) AS avg_confidence\nFROM sensor_data\nWHERE $__timeFilter(time)\n  AND common_name IN ($specie)\n  AND common_name NOT IN(${exclude:sqlstring})\n  AND confidence >= $confidence \n"
      }
     ]
    },
    {
     "title": "Avg Audio Length (Sec)",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 12, "y": 84 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  AVG(end_seconds - start_seconds) AS avg_audio_length_seconds\nFROM sensor_data\nWHERE $__timeFilter(time)\n  AND common_name IN ($specie)\n"
      }
     ]
    },
    {
     "title": "Avg Detections per Hour",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 16, "y": 84 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  count(*) * 3600.0\n    / extract(\n        epoch\n        FROM $__timeTo()::timestamp\n          - $__timeFrom()::timestamp\n      )\n  AS avg_per_hour\nFROM sensor_data\nWHERE $__timeFilter(time);\n"
      }
     ]
    },
    {
     "title": "Window Length (hrs)",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 20, "y": 84 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  extract(\n    epoch\n    FROM $__timeTo()::timestamp\n      - $__timeFrom()::timestamp\n  ) \n  / 3600.0\n  AS window_hours;\n"
      }
     ]
    },
    {
     "title": "Panel Title",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 267 },
     "targets": [
      {
       "rawSql": "SELECT\n  date_trunc('day', time)                        AS \"time\",\n  count(*)                                        AS total_obs,\n  count(DISTINCT scientific_name)                  AS species_count\nFROM sensor_data\nWHERE $__timeFilter(time)\nGROUP BY 1\nORDER BY 1;\n"
      }
     ]
    },
    {
     "title": "Activity Pattern Detection Distribution (Hrs)",
     "type": "heatmap",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 281 },
     "targets": [
      {
       "rawSql": "SELECT\n  extract(hour from time) AS detection_hour,\n  COUNT(*) AS \" \"\nFROM sensor_data\nWHERE $__timeFilter(time)\n  AND common_name IN ($specie)\n  AND common_name NOT IN(${exclude:sqlstring})\n  AND confidence >= $confidence \nGROUP BY detection_hour\nORDER BY detection_hour;"
      }
     ]
    },
    {
     "title": "Species Distribution",
     "type": "bargauge",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 284 },
     "options": { "reduceOptions": { "calcs": [ "first" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  common_name,\n  COUNT(*) AS total_by_species\nFROM sensor_data\nWHERE $__timeFilter(time)\n  AND common_name IN ($specie)\n  AND common_name NOT IN (${exclude:sqlstring})\n  AND confidence >= $confidence \nGROUP BY common_name\nORDER BY total_by_species DESC;\n"
      }
     ]
    },
    {
     "title": "Sensor 2",
     "type": "histogram",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 284 },
     "targets": [
      {
       "rawSql": "SELECT\r\n  time AS timestamp,\r\n  confidence\r\nFROM\r\n  sensor_data\r\nWHERE $__timeFilter(time)\r\nORDER BY\r\n  timestamp ASC;"
      }
     ]
    },
    {
     "title": "Panel Title",
     "type": "status-history",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 293 },
     "targets": [
      {
       "rawSql": "SELECT\n  date_trunc('day', time)     AS date,\n  common_name                 AS species,\n  COUNT(*)                    AS cnt\nFROM sensor_data\nWHERE $__timeFilter(time)\n  AND confidence >= $confidence\n  AND common_name IN ($specie)\nGROUP BY 1,2\nORDER BY 1,2;\n"
      }
     ]
    },
    {
     "title": "Raw Table Integration",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 304 },
     "targets": [
      {
       "rawSql": "SELECT\n  time,\n  start_seconds,\n  end_seconds,\n  scientific_name,\n  common_name,\n  confidence,\n  sensor_id\nFROM sensor_data\nWHERE $__timeFilter(time)\n  AND common_name IN ($specie)\n  AND common_name NOT IN(${exclude:sqlstring})\n  AND confidence >= $confidence \n"
      }
     ]
    },
    {
     "title": "Species Detection Confidence Over Time",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 314 },
     "targets": [
      {
       "rawSql": "SELECT\n  time AS \"time\",\n  confidence,\n  scientific_name\nFROM sensor_data\nWHERE $__timeFilter(time)\n  AND common_name IN ($specie)\n  AND common_name NOT IN(${exclude:sqlstring})\n  AND confidence >= $confidence \nORDER BY time ASC\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Sprint 3 Dashboard Iteration",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 103 },
   "collapsed": true,
   "panels": [
    {
     "title": "Observations (Total)",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 114 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT \n  count(*) AS total_detections\nFROM sensor_data\nWHERE $__timeFilter(time)\n"
      }
     ]
    },
    {
     "title": "Species (Unique)",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 114 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  count(DISTINCT common_name) AS unique_species\nFROM sensor_data\nWHERE $__timeFilter(time)\n\n"
      }
     ]
    },
    {
     "title": "Average Audio Length (Sec)",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 114 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  AVG(end_seconds - start_seconds) AS avg_audio_length_seconds\nFROM sensor_data\nWHERE $__timeFilter(\"time\");\n\n"
      }
     ]
    },
    {
     "title": "Average Confidence (Total)",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 114 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT \n  avg(confidence) AS avg_confidence\nFROM sensor_data\nWHERE $__timeFilter(time)\n\n"
      }
     ]
    },
    {
     "title": "Activity Pattern Detection Distribution (Hourly)",
     "type": "heatmap",
     "gridPos": { "h": 4, "w": 8, "x": 16, "y": 114 },
     "targets": [
      {
       "rawSql": "SELECT\n  extract(hour from time) AS detection_hour,\n  COUNT(*) AS detections\nFROM sensor_data\nWHERE $__timeFilter(time)\nGROUP BY detection_hour\nORDER BY detection_hour;"
      }
     ]
    },
    {
     "title": "Total Detection Counts (Daily)",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 16, "x": 0, "y": 118 },
     "targets": [
      {
       "rawSql": "SELECT \n  time_bucket('1 day', time) as day,\n  count(*) as total_detections\nFROM sensor_data \nWHERE $__timeFilter(time)\nGROUP BY day\nORDER BY day\n"
      }
     ]
    },
    {
     "title": "Recent Observations",
     "type": "table",
     "gridPos": { "h": 11, "w": 8, "x": 16, "y": 118 },
     "targets": [
      {
       "rawSql": "SELECT\n  time AS \"Detection Time\",\n  -- scientific_name AS \"Sci Name\",\n  common_name AS \"Common Name\",\n  confidence AS \"Confidence\"\nFROM sensor_data\nWHERE $__timeFilter(time)\nORDER BY time DESC\nLIMIT 10;\n"
      }
     ]
    },
    {
     "title": "Species Distribution",
     "type": "piechart",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 129 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  common_name,\n  COUNT(*) AS total_by_species\nFROM sensor_data\nWHERE $__timeFilter(sensor_data.time)\nGROUP BY common_name\nORDER BY total_by_species DESC;\n"
      }
     ]
    },
    {
     "title": "Average Confidence Species Detection (Daily)",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 16, "x": 8, "y": 129 },
     "targets": [
      {
       "rawSql": "SELECT \n  time_bucket('1 day', sensor_data.time) AS \"time\",\n  common_name AS species, \n  AVG(confidence) AS avg\nFROM sensor_data\nWHERE $__timeFilter(sensor_data.time)\nGROUP BY 1, species\nORDER BY 1 ASC, species ASC\n"
      }
     ]
    },
    {
     "title": "Raw Table Integration",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 140 },
     "targets": [
      {
       "rawSql": "SELECT\n  time,\n  start_seconds,\n  end_seconds,\n  scientific_name,\n  common_name,\n  confidence,\n  sensor_id\nFROM sensor_data\nWHERE $__timeFilter(time)\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Drafting",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 104 },
   "collapsed": true,
   "panels": [
    {
     "title": "Recent Observations",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 76 },
     "targets": [
      {
       "rawSql": "SELECT\n  time AS \"Detection Time\",\n  scientific_name AS \"Sci Name\",\n  common_name AS \"Common Name\",\n  confidence AS \"Confidence\"\nFROM sensor_data\nWHERE $__timeFilter(time)\n  AND common_name IN ($specie)\n  AND common_name NOT IN(${exclude:sqlstring})\n  AND confidence >= $confidence \nORDER BY time DESC\nLIMIT 10;\n"
      }
     ]
    },
    {
     "title": "Species Detection Confidence Over Time",
     "type": "candlestick",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 678 },
     "targets": [
      {
       "rawSql": "WITH stats AS (\n  SELECT\n    $__timeGroup(time,'1d')   AS bucket_time,\n    min(confidence)            AS low,\n    percentile_cont(0.25)\n      WITHIN GROUP (ORDER BY confidence) AS open,\n    percentile_cont(0.75)\n      WITHIN GROUP (ORDER BY confidence) AS close,\n    max(confidence)            AS high,\n    count(*)                   AS volume\n  FROM sensor_data\n  WHERE $__timeFilter(time)\n  GROUP BY 1\n)\nSELECT\n  bucket_time AS \"time\",\n  open, high, low, close, volume\nFROM stats\nORDER BY bucket_time;\n"
      }
     ]
    },
    {
     "title": "Panel Title",
     "type": "heatmap",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 780 },
     "targets": [
      {
       "rawSql": "SELECT\n  date_trunc('day', time)     AS date,\n  common_name                 AS species,\n  COUNT(*)                    AS cnt\nFROM sensor_data\nWHERE $__timeFilter(time)\n  AND confidence >= $confidence\n  AND common_name IN ($specie)\nGROUP BY 1,2\nORDER BY 1,2;\n"
      }
     ]
    },
    {
     "title": "Panel Title",
     "type": "heatmap",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 792 },
     "targets": [
      {
       "rawSql": "SELECT\n  date_trunc('day', time)     AS date,\n  common_name                 AS species,\n  COUNT(*)                    AS cnt\nFROM sensor_data\nWHERE $__timeFilter(time)\n  AND confidence >= $confidence\n  AND common_name IN ($specie)\nGROUP BY 1,2\nORDER BY 1,2;\n"
      }
     ]
    },
    {
     "title": "Species Detection Confidence Over Time",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 804 },
     "targets": [
      {
       "rawSql": "SELECT\n  time AS \"time\",\n  confidence,\n  scientific_name\nFROM sensor_data\nWHERE $__timeFilter(time)\nORDER BY time ASC\n"
      }
     ]
    },
    {
     "title": "Species Detection Confidence Over Time",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 815 },
     "targets": [
      {
       "rawSql": "SELECT\n  time_bucket('1h', time) AS bucket,\n  percentile_cont(0.25) WITHIN GROUP (ORDER BY confidence) AS q1,\n  percentile_cont(0.50) WITHIN GROUP (ORDER BY confidence) AS median,\n  percentile_cont(0.75) WITHIN GROUP (ORDER BY confidence) AS q3\nFROM sensor_data\nWHERE $__timeFilter(time)\nGROUP BY bucket\nORDER BY bucket;\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Species Breakdown",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 105 },
   "collapsed": true
  }
 ]
}